version: '3'

networks:
  pdns_net:
    ipam:
      driver: default
      config:
        - subnet: 172.53.0.0/16

services:
  pdns:
    container_name: pdns
    hostname: pdns
    build:
      context: ./pdns/
      dockerfile: ./Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - PDNS_API_KEY=${PDNS_API_KEY}
        - TIMEZONE=${TIMEZONE}
    image: pdns
    ports:
      - ${ALLOW_IPADDR}:8081:8081
    links:
      - mariadb
      - graphite
    depends_on:
      - mariadb
      - graphite
    entrypoint: "/bin/sh -c '/usr/sbin/rsyslogd && /usr/sbin/pdns_server'"
    restart: always
    networks:
      pdns_net:
        ipv4_address: 172.53.1.1

  pdns_recursor:
    container_name: pdns_recursor
    hostname: pdns_recursor
    build:
      context: ./pdns/
      dockerfile: ./pdns_recursor.Dockerfile
      args:
        - PDNS_API_KEY=${PDNS_API_KEY}
        - TIMEZONE=${TIMEZONE}
        - PDNS_RECURSOR_IPADDR=${PDNS_RECURSOR_IPADDR}
    image: pdns_recursor
    volumes:
      - ./pdns/conf/forward-zones-file:/etc/pdns/forward-zones-file
    ports:
      - ${ALLOW_IPADDR}:53:53
      - ${ALLOW_IPADDR}:53:53/udp
      - ${ALLOW_IPADDR}:8082:8082
    links:
      - pdns
      - graphite
    depends_on:
      - pdns
      - graphite
    entrypoint: "/bin/sh -c '/usr/sbin/rsyslogd && /usr/sbin/pdns_recursor'"
    restart: always
    networks:
      pdns_net:

  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - ./db_datadir:/var/lib/mysql
      - ./MariaDB:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      pdns_net:

  djangopowerdns:
    container_name: djangopowerdns
    build:
      context: ./DjangoPowerDNS
      dockerfile: ./Dockerfile
      args:
        - DJANGO_SU_NAME=${DJANGO_SU_NAME}
        - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
        - DJANGO_SU_PASSWD=${DJANGO_SU_PASSWD}
    image: djangopowerdns
    ports:
      - ${ALLOW_IPADDR}:8053:8053
    links:
      - mariadb
      - pdns
    depends_on:
      - mariadb
    restart: unless-stopped
    entrypoint: dockerize -wait tcp://mariadb:3306 /bin/bash ./run.sh
    networks:
      pdns_net:

  graphite:
    container_name: graphite
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - ${ALLOW_IPADDR}:8096:80
    networks:
      pdns_net:
        ipv4_address: 172.53.1.96