version: '3'
services:
  pdns:
    build:
      context: ./pdns/
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: pdns
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:8081:8081
    links:
      - mariadb
    depends_on:
      - mariadb
    entrypoint: /bin/bash /tmp/run.sh
    restart: always

  mariadb:
    image: mariadb
    volumes:
      - ./db_datadir:/var/lib/mysql
      - ./MariaDB:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  djangopowerdns:
    build:
      context: ./DjangoPowerDNS
      dockerfile: ./Dockerfile
      args:
        - DJANGO_SU_NAME=${DJANGO_SU_NAME}
        - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
        - DJANGO_SU_PASSWD=${DJANGO_SU_PASSWD}
    image: djangopowerdns
    ports:
      - 127.0.0.1:8053:8053
    links:
      - mariadb
      - pdns
    depends_on:
      - mariadb
    restart: unless-stopped
    entrypoint: dockerize -wait tcp://mariadb:3306 /bin/bash ./run.sh
